/*
 * Market Project REST API
 * REST API for managing categories and products
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mmartsiusheu@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.market.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Basic details about Category
 */
@ApiModel(description = "Basic details about Category")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-22T14:53:20.703+03:00")
public class CategoryDTO {
  @JsonProperty("categoryName")
  private String categoryName = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("parentId")
  private Long parentId = null;

  public CategoryDTO categoryName(String categoryName) {
    this.categoryName = categoryName;
    return this;
  }

   /**
   * Category name
   * @return categoryName
  **/
  @ApiModelProperty(value = "Category name")
  public String getCategoryName() {
    return categoryName;
  }

  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }

  public CategoryDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * The database generated category ID
   * @return id
  **/
  @ApiModelProperty(value = "The database generated category ID")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public CategoryDTO parentId(Long parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * Category parent id
   * @return parentId
  **/
  @ApiModelProperty(value = "Category parent id")
  public Long getParentId() {
    return parentId;
  }

  public void setParentId(Long parentId) {
    this.parentId = parentId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CategoryDTO categoryDTO = (CategoryDTO) o;
    return Objects.equals(this.categoryName, categoryDTO.categoryName) &&
        Objects.equals(this.id, categoryDTO.id) &&
        Objects.equals(this.parentId, categoryDTO.parentId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categoryName, id, parentId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CategoryDTO {\n");
    
    sb.append("    categoryName: ").append(toIndentedString(categoryName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

