/*
 * Market Project REST API
 * REST API for managing categories and products
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mmartsiusheu@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.market.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * Basic details about Product
 */
@ApiModel(description = "Basic details about Product")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-22T14:53:20.703+03:00")
public class ProductDTO {
  @JsonProperty("categoryId")
  private Long categoryId = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("productName")
  private String productName = null;

  @JsonProperty("productPrice")
  private BigDecimal productPrice = null;

  @JsonProperty("vendor")
  private String vendor = null;

  @JsonProperty("vendorCode")
  private String vendorCode = null;

  public ProductDTO categoryId(Long categoryId) {
    this.categoryId = categoryId;
    return this;
  }

   /**
   * Product category id
   * @return categoryId
  **/
  @ApiModelProperty(value = "Product category id")
  public Long getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(Long categoryId) {
    this.categoryId = categoryId;
  }

  public ProductDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * The database generated product ID
   * @return id
  **/
  @ApiModelProperty(value = "The database generated product ID")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ProductDTO productName(String productName) {
    this.productName = productName;
    return this;
  }

   /**
   * Product name
   * @return productName
  **/
  @ApiModelProperty(value = "Product name")
  public String getProductName() {
    return productName;
  }

  public void setProductName(String productName) {
    this.productName = productName;
  }

  public ProductDTO productPrice(BigDecimal productPrice) {
    this.productPrice = productPrice;
    return this;
  }

   /**
   * Product price
   * @return productPrice
  **/
  @ApiModelProperty(value = "Product price")
  public BigDecimal getProductPrice() {
    return productPrice;
  }

  public void setProductPrice(BigDecimal productPrice) {
    this.productPrice = productPrice;
  }

  public ProductDTO vendor(String vendor) {
    this.vendor = vendor;
    return this;
  }

   /**
   * Product vendor name
   * @return vendor
  **/
  @ApiModelProperty(value = "Product vendor name")
  public String getVendor() {
    return vendor;
  }

  public void setVendor(String vendor) {
    this.vendor = vendor;
  }

  public ProductDTO vendorCode(String vendorCode) {
    this.vendorCode = vendorCode;
    return this;
  }

   /**
   * Product vendor code
   * @return vendorCode
  **/
  @ApiModelProperty(value = "Product vendor code")
  public String getVendorCode() {
    return vendorCode;
  }

  public void setVendorCode(String vendorCode) {
    this.vendorCode = vendorCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductDTO productDTO = (ProductDTO) o;
    return Objects.equals(this.categoryId, productDTO.categoryId) &&
        Objects.equals(this.id, productDTO.id) &&
        Objects.equals(this.productName, productDTO.productName) &&
        Objects.equals(this.productPrice, productDTO.productPrice) &&
        Objects.equals(this.vendor, productDTO.vendor) &&
        Objects.equals(this.vendorCode, productDTO.vendorCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categoryId, id, productName, productPrice, vendor, vendorCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductDTO {\n");
    
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
    sb.append("    productPrice: ").append(toIndentedString(productPrice)).append("\n");
    sb.append("    vendor: ").append(toIndentedString(vendor)).append("\n");
    sb.append("    vendorCode: ").append(toIndentedString(vendorCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

